package com.qtatelier.OASystem.basics.linkdutydept.mapper;


import com.qtatelier.OASystem.basics.linkdutydept.model.LinkDutyDept;
import com.qtatelier.OASystem.request.DutyReq;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface LinkDutyDeptMapper
{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_duty_dept
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey( String linkId );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_duty_dept
     *
     * @mbg.generated
     */
    int insert( DutyReq record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_duty_dept
     *
     * @mbg.generated
     */
    LinkDutyDept selectByPrimaryKey( String linkId );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_duty_dept
     *
     * @mbg.generated
     */
    List<LinkDutyDept> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_duty_dept
     *
     * @mbg.generated
     */
    int updateByPrimaryKey( LinkDutyDept record );


    int deleteByDutyId( String dutyId);
}