package com.qtatelier.OASystem.basics.revisit_log.mapper;

import com.qtatelier.OASystem.basics.revisit_log.model.RevisitLog;
import com.qtatelier.OASystem.basics.revisit_log.model.RevisitLogExample;
import com.qtatelier.OASystem.request.RevisitLogReq;
import com.qtatelier.OASystem.response.RevisitLogRes;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface RevisitLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revisit_log
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int countByExample(RevisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revisit_log
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int deleteByExample(RevisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revisit_log
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int deleteByPrimaryKey(String revisitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revisit_log
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int insert(RevisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revisit_log
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int insertSelective(RevisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revisit_log
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    List<RevisitLog> selectByExample(RevisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revisit_log
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    RevisitLog selectByPrimaryKey(String revisitId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revisit_log
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") RevisitLog record, @Param("example") RevisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revisit_log
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int updateByExample(@Param("record") RevisitLog record, @Param("example") RevisitLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revisit_log
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int updateByPrimaryKeySelective(RevisitLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table revisit_log
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int updateByPrimaryKey(RevisitLog record);

    List<RevisitLogRes> findRevisitLog(RevisitLogReq revisitLogReq);
}