package com.qtatelier.OASystem.basics.dutyinfo.model;

import java.io.Serializable;

public class DutyInfo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duty_info.duty_id
     *
     * @mbg.generated
     */
    private String dutyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duty_info.duty_name
     *
     * @mbg.generated
     */
    private String dutyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column duty_info.duty_description
     *
     * @mbg.generated
     */
    private String dutyDescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table duty_info
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duty_info.duty_id
     *
     * @return the value of duty_info.duty_id
     *
     * @mbg.generated
     */
    public String getDutyId() {
        return dutyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duty_info.duty_id
     *
     * @param dutyId the value for duty_info.duty_id
     *
     * @mbg.generated
     */
    public void setDutyId(String dutyId) {
        this.dutyId = dutyId == null ? null : dutyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duty_info.duty_name
     *
     * @return the value of duty_info.duty_name
     *
     * @mbg.generated
     */
    public String getDutyName() {
        return dutyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duty_info.duty_name
     *
     * @param dutyName the value for duty_info.duty_name
     *
     * @mbg.generated
     */
    public void setDutyName(String dutyName) {
        this.dutyName = dutyName == null ? null : dutyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column duty_info.duty_description
     *
     * @return the value of duty_info.duty_description
     *
     * @mbg.generated
     */
    public String getDutyDescription() {
        return dutyDescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column duty_info.duty_description
     *
     * @param dutyDescription the value for duty_info.duty_description
     *
     * @mbg.generated
     */
    public void setDutyDescription(String dutyDescription) {
        this.dutyDescription = dutyDescription == null ? null : dutyDescription.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty_info
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dutyId=").append(dutyId);
        sb.append(", dutyName=").append(dutyName);
        sb.append(", dutyDescription=").append(dutyDescription);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}