package com.qtatelier.OASystem.basics.linkdutydept.model;

import java.io.Serializable;

public class LinkDutyDept implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_duty_dept.link__id
     *
     * @mbg.generated
     */
    private String linkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_duty_dept.duty_id
     *
     * @mbg.generated
     */
    private String dutyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_duty_dept.dept_id
     *
     * @mbg.generated
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table link_duty_dept
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_duty_dept.link__id
     *
     * @return the value of link_duty_dept.link__id
     *
     * @mbg.generated
     */
    public String getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_duty_dept.link__id
     *
     * @param linkId the value for link_duty_dept.link__id
     *
     * @mbg.generated
     */
    public void setLinkId(String linkId) {
        this.linkId = linkId == null ? null : linkId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_duty_dept.duty_id
     *
     * @return the value of link_duty_dept.duty_id
     *
     * @mbg.generated
     */
    public String getDutyId() {
        return dutyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_duty_dept.duty_id
     *
     * @param dutyId the value for link_duty_dept.duty_id
     *
     * @mbg.generated
     */
    public void setDutyId(String dutyId) {
        this.dutyId = dutyId == null ? null : dutyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_duty_dept.dept_id
     *
     * @return the value of link_duty_dept.dept_id
     *
     * @mbg.generated
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_duty_dept.dept_id
     *
     * @param deptId the value for link_duty_dept.dept_id
     *
     * @mbg.generated
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId == null ? null : deptId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_duty_dept
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", linkId=").append(linkId);
        sb.append(", dutyId=").append(dutyId);
        sb.append(", deptId=").append(deptId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}