package com.qtatelier.OASystem.basics.empinfo.model;

public class empInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_info.emp_id
     *
     * @mbggenerated Sun Jan 12 19:24:38 CST 2020
     */
    private String empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_info.emp_no
     *
     * @mbggenerated Sun Jan 12 19:24:38 CST 2020
     */
    private String empNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column emp_info.emp_duties
     *
     * @mbggenerated Sun Jan 12 19:24:38 CST 2020
     */
    private String empDuties;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_info.emp_id
     *
     * @return the value of emp_info.emp_id
     *
     * @mbggenerated Sun Jan 12 19:24:38 CST 2020
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_info.emp_id
     *
     * @param empId the value for emp_info.emp_id
     *
     * @mbggenerated Sun Jan 12 19:24:38 CST 2020
     */
    public void setEmpId(String empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_info.emp_no
     *
     * @return the value of emp_info.emp_no
     *
     * @mbggenerated Sun Jan 12 19:24:38 CST 2020
     */
    public String getEmpNo() {
        return empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_info.emp_no
     *
     * @param empNo the value for emp_info.emp_no
     *
     * @mbggenerated Sun Jan 12 19:24:38 CST 2020
     */
    public void setEmpNo(String empNo) {
        this.empNo = empNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column emp_info.emp_duties
     *
     * @return the value of emp_info.emp_duties
     *
     * @mbggenerated Sun Jan 12 19:24:38 CST 2020
     */
    public String getEmpDuties() {
        return empDuties;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column emp_info.emp_duties
     *
     * @param empDuties the value for emp_info.emp_duties
     *
     * @mbggenerated Sun Jan 12 19:24:38 CST 2020
     */
    public void setEmpDuties(String empDuties) {
        this.empDuties = empDuties;
    }
}