package com.qtatelier.OASystem.basics.linkroleuser.model;

public class LinkRoleUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_role_user.link_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    private String linkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_role_user.role_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_role_user.user_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_role_user.link_id
     *
     * @return the value of link_role_user.link_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public String getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_role_user.link_id
     *
     * @param linkId the value for link_role_user.link_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public void setLinkId(String linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_role_user.role_id
     *
     * @return the value of link_role_user.role_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_role_user.role_id
     *
     * @param roleId the value for link_role_user.role_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_role_user.user_id
     *
     * @return the value of link_role_user.user_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_role_user.user_id
     *
     * @param userId the value for link_role_user.user_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}