package com.qtatelier.OASystem.basics.link_user_customer.model;

public class LinkUserCustomer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_user_customer.link_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String linkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_user_customer.user_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_user_customer.customer_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_user_customer.link_id
     *
     * @return the value of link_user_customer.link_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_user_customer.link_id
     *
     * @param linkId the value for link_user_customer.link_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setLinkId(String linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_user_customer.user_id
     *
     * @return the value of link_user_customer.user_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_user_customer.user_id
     *
     * @param userId the value for link_user_customer.user_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_user_customer.customer_id
     *
     * @return the value of link_user_customer.customer_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_user_customer.customer_id
     *
     * @param customerId the value for link_user_customer.customer_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }
}