package com.qtatelier.OASystem.basics.optlog.mapper;

import com.qtatelier.OASystem.basics.optlog.model.OptLog;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface OptLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey( String logId );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_log
     *
     * @mbg.generated
     */
    int insert( OptLog record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_log
     *
     * @mbg.generated
     */
    OptLog selectByPrimaryKey( String logId );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_log
     *
     * @mbg.generated
     */
    List<OptLog> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table opt_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey( OptLog record );


    int deleteInfoByLike(String operTime);


    List<OptLog> selectByAccoutId(OptLog optLog);
}