package com.qtatelier.OASystem.basics.deptinfo.mapper;


import com.qtatelier.OASystem.basics.deptinfo.model.DeptInfo;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface DeptInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int deleteByPrimaryKey(String deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int insert(DeptInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int insertSelective(DeptInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    DeptInfo selectByPrimaryKey(String deptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int updateByPrimaryKeySelective(DeptInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dept_info
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int updateByPrimaryKey(DeptInfo record);
}