package com.qtatelier.OASystem.basics.link_customer_revisit.model;

public class LinkCustomerRevisit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_customer_revisit.link_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String linkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_customer_revisit.customer_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_customer_revisit.revisit_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String revisitId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_customer_revisit.link_id
     *
     * @return the value of link_customer_revisit.link_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_customer_revisit.link_id
     *
     * @param linkId the value for link_customer_revisit.link_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setLinkId(String linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_customer_revisit.customer_id
     *
     * @return the value of link_customer_revisit.customer_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_customer_revisit.customer_id
     *
     * @param customerId the value for link_customer_revisit.customer_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_customer_revisit.revisit_id
     *
     * @return the value of link_customer_revisit.revisit_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getRevisitId() {
        return revisitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_customer_revisit.revisit_id
     *
     * @param revisitId the value for link_customer_revisit.revisit_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setRevisitId(String revisitId) {
        this.revisitId = revisitId;
    }
}