package com.qtatelier.OASystem.basics.customerinfo.model;

public class CustomerInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.customer_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.customer_name
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String customerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.customer_contact
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String customerContact;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.customer_address
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String customerAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.sign_date
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String signDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.pay_free
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String payFree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.back_no
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String backNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.customer_phone
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String customerPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.contract
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String contract;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.remark
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.ftp
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String ftp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.load
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String load;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.author
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String author;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.suggestion_one
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String suggestionOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.suggestion_two
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String suggestionTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column customer_info.suggestion_three
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String suggestionThree;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.customer_id
     *
     * @return the value of customer_info.customer_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.customer_id
     *
     * @param customerId the value for customer_info.customer_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setCustomerId(String customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.customer_name
     *
     * @return the value of customer_info.customer_name
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getCustomerName() {
        return customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.customer_name
     *
     * @param customerName the value for customer_info.customer_name
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setCustomerName(String customerName) {
        this.customerName = customerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.customer_contact
     *
     * @return the value of customer_info.customer_contact
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getCustomerContact() {
        return customerContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.customer_contact
     *
     * @param customerContact the value for customer_info.customer_contact
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setCustomerContact(String customerContact) {
        this.customerContact = customerContact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.customer_address
     *
     * @return the value of customer_info.customer_address
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getCustomerAddress() {
        return customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.customer_address
     *
     * @param customerAddress the value for customer_info.customer_address
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setCustomerAddress(String customerAddress) {
        this.customerAddress = customerAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.sign_date
     *
     * @return the value of customer_info.sign_date
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getSignDate() {
        return signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.sign_date
     *
     * @param signDate the value for customer_info.sign_date
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setSignDate(String signDate) {
        this.signDate = signDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.pay_free
     *
     * @return the value of customer_info.pay_free
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getPayFree() {
        return payFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.pay_free
     *
     * @param payFree the value for customer_info.pay_free
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setPayFree(String payFree) {
        this.payFree = payFree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.back_no
     *
     * @return the value of customer_info.back_no
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getBackNo() {
        return backNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.back_no
     *
     * @param backNo the value for customer_info.back_no
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setBackNo(String backNo) {
        this.backNo = backNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.customer_phone
     *
     * @return the value of customer_info.customer_phone
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getCustomerPhone() {
        return customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.customer_phone
     *
     * @param customerPhone the value for customer_info.customer_phone
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setCustomerPhone(String customerPhone) {
        this.customerPhone = customerPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.contract
     *
     * @return the value of customer_info.contract
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getContract() {
        return contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.contract
     *
     * @param contract the value for customer_info.contract
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setContract(String contract) {
        this.contract = contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.remark
     *
     * @return the value of customer_info.remark
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.remark
     *
     * @param remark the value for customer_info.remark
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.ftp
     *
     * @return the value of customer_info.ftp
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getFtp() {
        return ftp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.ftp
     *
     * @param ftp the value for customer_info.ftp
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setFtp(String ftp) {
        this.ftp = ftp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.load
     *
     * @return the value of customer_info.load
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getLoad() {
        return load;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.load
     *
     * @param load the value for customer_info.load
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setLoad(String load) {
        this.load = load;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.author
     *
     * @return the value of customer_info.author
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.author
     *
     * @param author the value for customer_info.author
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.suggestion_one
     *
     * @return the value of customer_info.suggestion_one
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getSuggestionOne() {
        return suggestionOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.suggestion_one
     *
     * @param suggestionOne the value for customer_info.suggestion_one
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setSuggestionOne(String suggestionOne) {
        this.suggestionOne = suggestionOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.suggestion_two
     *
     * @return the value of customer_info.suggestion_two
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getSuggestionTwo() {
        return suggestionTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.suggestion_two
     *
     * @param suggestionTwo the value for customer_info.suggestion_two
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setSuggestionTwo(String suggestionTwo) {
        this.suggestionTwo = suggestionTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column customer_info.suggestion_three
     *
     * @return the value of customer_info.suggestion_three
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getSuggestionThree() {
        return suggestionThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column customer_info.suggestion_three
     *
     * @param suggestionThree the value for customer_info.suggestion_three
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setSuggestionThree(String suggestionThree) {
        this.suggestionThree = suggestionThree;
    }
}