package com.qtatelier.OASystem.basics.customerinfo.model;

import java.util.ArrayList;
import java.util.List;

public class CustomerInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public CustomerInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andCustomerIdIsNull() {
            addCriterion("customer_id is null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIsNotNull() {
            addCriterion("customer_id is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerIdEqualTo(String value) {
            addCriterion("customer_id =", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotEqualTo(String value) {
            addCriterion("customer_id <>", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThan(String value) {
            addCriterion("customer_id >", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdGreaterThanOrEqualTo(String value) {
            addCriterion("customer_id >=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThan(String value) {
            addCriterion("customer_id <", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLessThanOrEqualTo(String value) {
            addCriterion("customer_id <=", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdLike(String value) {
            addCriterion("customer_id like", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotLike(String value) {
            addCriterion("customer_id not like", value, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdIn(List<String> values) {
            addCriterion("customer_id in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotIn(List<String> values) {
            addCriterion("customer_id not in", values, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdBetween(String value1, String value2) {
            addCriterion("customer_id between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerIdNotBetween(String value1, String value2) {
            addCriterion("customer_id not between", value1, value2, "customerId");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNull() {
            addCriterion("customer_name is null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIsNotNull() {
            addCriterion("customer_name is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerNameEqualTo(String value) {
            addCriterion("customer_name =", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotEqualTo(String value) {
            addCriterion("customer_name <>", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThan(String value) {
            addCriterion("customer_name >", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameGreaterThanOrEqualTo(String value) {
            addCriterion("customer_name >=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThan(String value) {
            addCriterion("customer_name <", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLessThanOrEqualTo(String value) {
            addCriterion("customer_name <=", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameLike(String value) {
            addCriterion("customer_name like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotLike(String value) {
            addCriterion("customer_name not like", value, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameIn(List<String> values) {
            addCriterion("customer_name in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotIn(List<String> values) {
            addCriterion("customer_name not in", values, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameBetween(String value1, String value2) {
            addCriterion("customer_name between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerNameNotBetween(String value1, String value2) {
            addCriterion("customer_name not between", value1, value2, "customerName");
            return (Criteria) this;
        }

        public Criteria andCustomerContactIsNull() {
            addCriterion("customer_contact is null");
            return (Criteria) this;
        }

        public Criteria andCustomerContactIsNotNull() {
            addCriterion("customer_contact is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerContactEqualTo(String value) {
            addCriterion("customer_contact =", value, "customerContact");
            return (Criteria) this;
        }

        public Criteria andCustomerContactNotEqualTo(String value) {
            addCriterion("customer_contact <>", value, "customerContact");
            return (Criteria) this;
        }

        public Criteria andCustomerContactGreaterThan(String value) {
            addCriterion("customer_contact >", value, "customerContact");
            return (Criteria) this;
        }

        public Criteria andCustomerContactGreaterThanOrEqualTo(String value) {
            addCriterion("customer_contact >=", value, "customerContact");
            return (Criteria) this;
        }

        public Criteria andCustomerContactLessThan(String value) {
            addCriterion("customer_contact <", value, "customerContact");
            return (Criteria) this;
        }

        public Criteria andCustomerContactLessThanOrEqualTo(String value) {
            addCriterion("customer_contact <=", value, "customerContact");
            return (Criteria) this;
        }

        public Criteria andCustomerContactLike(String value) {
            addCriterion("customer_contact like", value, "customerContact");
            return (Criteria) this;
        }

        public Criteria andCustomerContactNotLike(String value) {
            addCriterion("customer_contact not like", value, "customerContact");
            return (Criteria) this;
        }

        public Criteria andCustomerContactIn(List<String> values) {
            addCriterion("customer_contact in", values, "customerContact");
            return (Criteria) this;
        }

        public Criteria andCustomerContactNotIn(List<String> values) {
            addCriterion("customer_contact not in", values, "customerContact");
            return (Criteria) this;
        }

        public Criteria andCustomerContactBetween(String value1, String value2) {
            addCriterion("customer_contact between", value1, value2, "customerContact");
            return (Criteria) this;
        }

        public Criteria andCustomerContactNotBetween(String value1, String value2) {
            addCriterion("customer_contact not between", value1, value2, "customerContact");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressIsNull() {
            addCriterion("customer_address is null");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressIsNotNull() {
            addCriterion("customer_address is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressEqualTo(String value) {
            addCriterion("customer_address =", value, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressNotEqualTo(String value) {
            addCriterion("customer_address <>", value, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressGreaterThan(String value) {
            addCriterion("customer_address >", value, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressGreaterThanOrEqualTo(String value) {
            addCriterion("customer_address >=", value, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressLessThan(String value) {
            addCriterion("customer_address <", value, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressLessThanOrEqualTo(String value) {
            addCriterion("customer_address <=", value, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressLike(String value) {
            addCriterion("customer_address like", value, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressNotLike(String value) {
            addCriterion("customer_address not like", value, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressIn(List<String> values) {
            addCriterion("customer_address in", values, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressNotIn(List<String> values) {
            addCriterion("customer_address not in", values, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressBetween(String value1, String value2) {
            addCriterion("customer_address between", value1, value2, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andCustomerAddressNotBetween(String value1, String value2) {
            addCriterion("customer_address not between", value1, value2, "customerAddress");
            return (Criteria) this;
        }

        public Criteria andSignDateIsNull() {
            addCriterion("sign_date is null");
            return (Criteria) this;
        }

        public Criteria andSignDateIsNotNull() {
            addCriterion("sign_date is not null");
            return (Criteria) this;
        }

        public Criteria andSignDateEqualTo(String value) {
            addCriterion("sign_date =", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateNotEqualTo(String value) {
            addCriterion("sign_date <>", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateGreaterThan(String value) {
            addCriterion("sign_date >", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateGreaterThanOrEqualTo(String value) {
            addCriterion("sign_date >=", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateLessThan(String value) {
            addCriterion("sign_date <", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateLessThanOrEqualTo(String value) {
            addCriterion("sign_date <=", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateLike(String value) {
            addCriterion("sign_date like", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateNotLike(String value) {
            addCriterion("sign_date not like", value, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateIn(List<String> values) {
            addCriterion("sign_date in", values, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateNotIn(List<String> values) {
            addCriterion("sign_date not in", values, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateBetween(String value1, String value2) {
            addCriterion("sign_date between", value1, value2, "signDate");
            return (Criteria) this;
        }

        public Criteria andSignDateNotBetween(String value1, String value2) {
            addCriterion("sign_date not between", value1, value2, "signDate");
            return (Criteria) this;
        }

        public Criteria andPayFreeIsNull() {
            addCriterion("pay_free is null");
            return (Criteria) this;
        }

        public Criteria andPayFreeIsNotNull() {
            addCriterion("pay_free is not null");
            return (Criteria) this;
        }

        public Criteria andPayFreeEqualTo(String value) {
            addCriterion("pay_free =", value, "payFree");
            return (Criteria) this;
        }

        public Criteria andPayFreeNotEqualTo(String value) {
            addCriterion("pay_free <>", value, "payFree");
            return (Criteria) this;
        }

        public Criteria andPayFreeGreaterThan(String value) {
            addCriterion("pay_free >", value, "payFree");
            return (Criteria) this;
        }

        public Criteria andPayFreeGreaterThanOrEqualTo(String value) {
            addCriterion("pay_free >=", value, "payFree");
            return (Criteria) this;
        }

        public Criteria andPayFreeLessThan(String value) {
            addCriterion("pay_free <", value, "payFree");
            return (Criteria) this;
        }

        public Criteria andPayFreeLessThanOrEqualTo(String value) {
            addCriterion("pay_free <=", value, "payFree");
            return (Criteria) this;
        }

        public Criteria andPayFreeLike(String value) {
            addCriterion("pay_free like", value, "payFree");
            return (Criteria) this;
        }

        public Criteria andPayFreeNotLike(String value) {
            addCriterion("pay_free not like", value, "payFree");
            return (Criteria) this;
        }

        public Criteria andPayFreeIn(List<String> values) {
            addCriterion("pay_free in", values, "payFree");
            return (Criteria) this;
        }

        public Criteria andPayFreeNotIn(List<String> values) {
            addCriterion("pay_free not in", values, "payFree");
            return (Criteria) this;
        }

        public Criteria andPayFreeBetween(String value1, String value2) {
            addCriterion("pay_free between", value1, value2, "payFree");
            return (Criteria) this;
        }

        public Criteria andPayFreeNotBetween(String value1, String value2) {
            addCriterion("pay_free not between", value1, value2, "payFree");
            return (Criteria) this;
        }

        public Criteria andBackNoIsNull() {
            addCriterion("back_no is null");
            return (Criteria) this;
        }

        public Criteria andBackNoIsNotNull() {
            addCriterion("back_no is not null");
            return (Criteria) this;
        }

        public Criteria andBackNoEqualTo(String value) {
            addCriterion("back_no =", value, "backNo");
            return (Criteria) this;
        }

        public Criteria andBackNoNotEqualTo(String value) {
            addCriterion("back_no <>", value, "backNo");
            return (Criteria) this;
        }

        public Criteria andBackNoGreaterThan(String value) {
            addCriterion("back_no >", value, "backNo");
            return (Criteria) this;
        }

        public Criteria andBackNoGreaterThanOrEqualTo(String value) {
            addCriterion("back_no >=", value, "backNo");
            return (Criteria) this;
        }

        public Criteria andBackNoLessThan(String value) {
            addCriterion("back_no <", value, "backNo");
            return (Criteria) this;
        }

        public Criteria andBackNoLessThanOrEqualTo(String value) {
            addCriterion("back_no <=", value, "backNo");
            return (Criteria) this;
        }

        public Criteria andBackNoLike(String value) {
            addCriterion("back_no like", value, "backNo");
            return (Criteria) this;
        }

        public Criteria andBackNoNotLike(String value) {
            addCriterion("back_no not like", value, "backNo");
            return (Criteria) this;
        }

        public Criteria andBackNoIn(List<String> values) {
            addCriterion("back_no in", values, "backNo");
            return (Criteria) this;
        }

        public Criteria andBackNoNotIn(List<String> values) {
            addCriterion("back_no not in", values, "backNo");
            return (Criteria) this;
        }

        public Criteria andBackNoBetween(String value1, String value2) {
            addCriterion("back_no between", value1, value2, "backNo");
            return (Criteria) this;
        }

        public Criteria andBackNoNotBetween(String value1, String value2) {
            addCriterion("back_no not between", value1, value2, "backNo");
            return (Criteria) this;
        }

        public Criteria andCustomerPhoneIsNull() {
            addCriterion("customer_phone is null");
            return (Criteria) this;
        }

        public Criteria andCustomerPhoneIsNotNull() {
            addCriterion("customer_phone is not null");
            return (Criteria) this;
        }

        public Criteria andCustomerPhoneEqualTo(String value) {
            addCriterion("customer_phone =", value, "customerPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerPhoneNotEqualTo(String value) {
            addCriterion("customer_phone <>", value, "customerPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerPhoneGreaterThan(String value) {
            addCriterion("customer_phone >", value, "customerPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("customer_phone >=", value, "customerPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerPhoneLessThan(String value) {
            addCriterion("customer_phone <", value, "customerPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerPhoneLessThanOrEqualTo(String value) {
            addCriterion("customer_phone <=", value, "customerPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerPhoneLike(String value) {
            addCriterion("customer_phone like", value, "customerPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerPhoneNotLike(String value) {
            addCriterion("customer_phone not like", value, "customerPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerPhoneIn(List<String> values) {
            addCriterion("customer_phone in", values, "customerPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerPhoneNotIn(List<String> values) {
            addCriterion("customer_phone not in", values, "customerPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerPhoneBetween(String value1, String value2) {
            addCriterion("customer_phone between", value1, value2, "customerPhone");
            return (Criteria) this;
        }

        public Criteria andCustomerPhoneNotBetween(String value1, String value2) {
            addCriterion("customer_phone not between", value1, value2, "customerPhone");
            return (Criteria) this;
        }

        public Criteria andContractIsNull() {
            addCriterion("contract is null");
            return (Criteria) this;
        }

        public Criteria andContractIsNotNull() {
            addCriterion("contract is not null");
            return (Criteria) this;
        }

        public Criteria andContractEqualTo(String value) {
            addCriterion("contract =", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractNotEqualTo(String value) {
            addCriterion("contract <>", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractGreaterThan(String value) {
            addCriterion("contract >", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractGreaterThanOrEqualTo(String value) {
            addCriterion("contract >=", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractLessThan(String value) {
            addCriterion("contract <", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractLessThanOrEqualTo(String value) {
            addCriterion("contract <=", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractLike(String value) {
            addCriterion("contract like", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractNotLike(String value) {
            addCriterion("contract not like", value, "contract");
            return (Criteria) this;
        }

        public Criteria andContractIn(List<String> values) {
            addCriterion("contract in", values, "contract");
            return (Criteria) this;
        }

        public Criteria andContractNotIn(List<String> values) {
            addCriterion("contract not in", values, "contract");
            return (Criteria) this;
        }

        public Criteria andContractBetween(String value1, String value2) {
            addCriterion("contract between", value1, value2, "contract");
            return (Criteria) this;
        }

        public Criteria andContractNotBetween(String value1, String value2) {
            addCriterion("contract not between", value1, value2, "contract");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andFtpIsNull() {
            addCriterion("ftp is null");
            return (Criteria) this;
        }

        public Criteria andFtpIsNotNull() {
            addCriterion("ftp is not null");
            return (Criteria) this;
        }

        public Criteria andFtpEqualTo(String value) {
            addCriterion("ftp =", value, "ftp");
            return (Criteria) this;
        }

        public Criteria andFtpNotEqualTo(String value) {
            addCriterion("ftp <>", value, "ftp");
            return (Criteria) this;
        }

        public Criteria andFtpGreaterThan(String value) {
            addCriterion("ftp >", value, "ftp");
            return (Criteria) this;
        }

        public Criteria andFtpGreaterThanOrEqualTo(String value) {
            addCriterion("ftp >=", value, "ftp");
            return (Criteria) this;
        }

        public Criteria andFtpLessThan(String value) {
            addCriterion("ftp <", value, "ftp");
            return (Criteria) this;
        }

        public Criteria andFtpLessThanOrEqualTo(String value) {
            addCriterion("ftp <=", value, "ftp");
            return (Criteria) this;
        }

        public Criteria andFtpLike(String value) {
            addCriterion("ftp like", value, "ftp");
            return (Criteria) this;
        }

        public Criteria andFtpNotLike(String value) {
            addCriterion("ftp not like", value, "ftp");
            return (Criteria) this;
        }

        public Criteria andFtpIn(List<String> values) {
            addCriterion("ftp in", values, "ftp");
            return (Criteria) this;
        }

        public Criteria andFtpNotIn(List<String> values) {
            addCriterion("ftp not in", values, "ftp");
            return (Criteria) this;
        }

        public Criteria andFtpBetween(String value1, String value2) {
            addCriterion("ftp between", value1, value2, "ftp");
            return (Criteria) this;
        }

        public Criteria andFtpNotBetween(String value1, String value2) {
            addCriterion("ftp not between", value1, value2, "ftp");
            return (Criteria) this;
        }

        public Criteria andLoadIsNull() {
            addCriterion("load is null");
            return (Criteria) this;
        }

        public Criteria andLoadIsNotNull() {
            addCriterion("load is not null");
            return (Criteria) this;
        }

        public Criteria andLoadEqualTo(String value) {
            addCriterion("load =", value, "load");
            return (Criteria) this;
        }

        public Criteria andLoadNotEqualTo(String value) {
            addCriterion("load <>", value, "load");
            return (Criteria) this;
        }

        public Criteria andLoadGreaterThan(String value) {
            addCriterion("load >", value, "load");
            return (Criteria) this;
        }

        public Criteria andLoadGreaterThanOrEqualTo(String value) {
            addCriterion("load >=", value, "load");
            return (Criteria) this;
        }

        public Criteria andLoadLessThan(String value) {
            addCriterion("load <", value, "load");
            return (Criteria) this;
        }

        public Criteria andLoadLessThanOrEqualTo(String value) {
            addCriterion("load <=", value, "load");
            return (Criteria) this;
        }

        public Criteria andLoadLike(String value) {
            addCriterion("load like", value, "load");
            return (Criteria) this;
        }

        public Criteria andLoadNotLike(String value) {
            addCriterion("load not like", value, "load");
            return (Criteria) this;
        }

        public Criteria andLoadIn(List<String> values) {
            addCriterion("load in", values, "load");
            return (Criteria) this;
        }

        public Criteria andLoadNotIn(List<String> values) {
            addCriterion("load not in", values, "load");
            return (Criteria) this;
        }

        public Criteria andLoadBetween(String value1, String value2) {
            addCriterion("load between", value1, value2, "load");
            return (Criteria) this;
        }

        public Criteria andLoadNotBetween(String value1, String value2) {
            addCriterion("load not between", value1, value2, "load");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("author is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("author is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(String value) {
            addCriterion("author =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(String value) {
            addCriterion("author <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(String value) {
            addCriterion("author >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("author >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(String value) {
            addCriterion("author <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(String value) {
            addCriterion("author <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLike(String value) {
            addCriterion("author like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotLike(String value) {
            addCriterion("author not like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<String> values) {
            addCriterion("author in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<String> values) {
            addCriterion("author not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(String value1, String value2) {
            addCriterion("author between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(String value1, String value2) {
            addCriterion("author not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andSuggestionOneIsNull() {
            addCriterion("suggestion_one is null");
            return (Criteria) this;
        }

        public Criteria andSuggestionOneIsNotNull() {
            addCriterion("suggestion_one is not null");
            return (Criteria) this;
        }

        public Criteria andSuggestionOneEqualTo(String value) {
            addCriterion("suggestion_one =", value, "suggestionOne");
            return (Criteria) this;
        }

        public Criteria andSuggestionOneNotEqualTo(String value) {
            addCriterion("suggestion_one <>", value, "suggestionOne");
            return (Criteria) this;
        }

        public Criteria andSuggestionOneGreaterThan(String value) {
            addCriterion("suggestion_one >", value, "suggestionOne");
            return (Criteria) this;
        }

        public Criteria andSuggestionOneGreaterThanOrEqualTo(String value) {
            addCriterion("suggestion_one >=", value, "suggestionOne");
            return (Criteria) this;
        }

        public Criteria andSuggestionOneLessThan(String value) {
            addCriterion("suggestion_one <", value, "suggestionOne");
            return (Criteria) this;
        }

        public Criteria andSuggestionOneLessThanOrEqualTo(String value) {
            addCriterion("suggestion_one <=", value, "suggestionOne");
            return (Criteria) this;
        }

        public Criteria andSuggestionOneLike(String value) {
            addCriterion("suggestion_one like", value, "suggestionOne");
            return (Criteria) this;
        }

        public Criteria andSuggestionOneNotLike(String value) {
            addCriterion("suggestion_one not like", value, "suggestionOne");
            return (Criteria) this;
        }

        public Criteria andSuggestionOneIn(List<String> values) {
            addCriterion("suggestion_one in", values, "suggestionOne");
            return (Criteria) this;
        }

        public Criteria andSuggestionOneNotIn(List<String> values) {
            addCriterion("suggestion_one not in", values, "suggestionOne");
            return (Criteria) this;
        }

        public Criteria andSuggestionOneBetween(String value1, String value2) {
            addCriterion("suggestion_one between", value1, value2, "suggestionOne");
            return (Criteria) this;
        }

        public Criteria andSuggestionOneNotBetween(String value1, String value2) {
            addCriterion("suggestion_one not between", value1, value2, "suggestionOne");
            return (Criteria) this;
        }

        public Criteria andSuggestionTwoIsNull() {
            addCriterion("suggestion_two is null");
            return (Criteria) this;
        }

        public Criteria andSuggestionTwoIsNotNull() {
            addCriterion("suggestion_two is not null");
            return (Criteria) this;
        }

        public Criteria andSuggestionTwoEqualTo(String value) {
            addCriterion("suggestion_two =", value, "suggestionTwo");
            return (Criteria) this;
        }

        public Criteria andSuggestionTwoNotEqualTo(String value) {
            addCriterion("suggestion_two <>", value, "suggestionTwo");
            return (Criteria) this;
        }

        public Criteria andSuggestionTwoGreaterThan(String value) {
            addCriterion("suggestion_two >", value, "suggestionTwo");
            return (Criteria) this;
        }

        public Criteria andSuggestionTwoGreaterThanOrEqualTo(String value) {
            addCriterion("suggestion_two >=", value, "suggestionTwo");
            return (Criteria) this;
        }

        public Criteria andSuggestionTwoLessThan(String value) {
            addCriterion("suggestion_two <", value, "suggestionTwo");
            return (Criteria) this;
        }

        public Criteria andSuggestionTwoLessThanOrEqualTo(String value) {
            addCriterion("suggestion_two <=", value, "suggestionTwo");
            return (Criteria) this;
        }

        public Criteria andSuggestionTwoLike(String value) {
            addCriterion("suggestion_two like", value, "suggestionTwo");
            return (Criteria) this;
        }

        public Criteria andSuggestionTwoNotLike(String value) {
            addCriterion("suggestion_two not like", value, "suggestionTwo");
            return (Criteria) this;
        }

        public Criteria andSuggestionTwoIn(List<String> values) {
            addCriterion("suggestion_two in", values, "suggestionTwo");
            return (Criteria) this;
        }

        public Criteria andSuggestionTwoNotIn(List<String> values) {
            addCriterion("suggestion_two not in", values, "suggestionTwo");
            return (Criteria) this;
        }

        public Criteria andSuggestionTwoBetween(String value1, String value2) {
            addCriterion("suggestion_two between", value1, value2, "suggestionTwo");
            return (Criteria) this;
        }

        public Criteria andSuggestionTwoNotBetween(String value1, String value2) {
            addCriterion("suggestion_two not between", value1, value2, "suggestionTwo");
            return (Criteria) this;
        }

        public Criteria andSuggestionThreeIsNull() {
            addCriterion("suggestion_three is null");
            return (Criteria) this;
        }

        public Criteria andSuggestionThreeIsNotNull() {
            addCriterion("suggestion_three is not null");
            return (Criteria) this;
        }

        public Criteria andSuggestionThreeEqualTo(String value) {
            addCriterion("suggestion_three =", value, "suggestionThree");
            return (Criteria) this;
        }

        public Criteria andSuggestionThreeNotEqualTo(String value) {
            addCriterion("suggestion_three <>", value, "suggestionThree");
            return (Criteria) this;
        }

        public Criteria andSuggestionThreeGreaterThan(String value) {
            addCriterion("suggestion_three >", value, "suggestionThree");
            return (Criteria) this;
        }

        public Criteria andSuggestionThreeGreaterThanOrEqualTo(String value) {
            addCriterion("suggestion_three >=", value, "suggestionThree");
            return (Criteria) this;
        }

        public Criteria andSuggestionThreeLessThan(String value) {
            addCriterion("suggestion_three <", value, "suggestionThree");
            return (Criteria) this;
        }

        public Criteria andSuggestionThreeLessThanOrEqualTo(String value) {
            addCriterion("suggestion_three <=", value, "suggestionThree");
            return (Criteria) this;
        }

        public Criteria andSuggestionThreeLike(String value) {
            addCriterion("suggestion_three like", value, "suggestionThree");
            return (Criteria) this;
        }

        public Criteria andSuggestionThreeNotLike(String value) {
            addCriterion("suggestion_three not like", value, "suggestionThree");
            return (Criteria) this;
        }

        public Criteria andSuggestionThreeIn(List<String> values) {
            addCriterion("suggestion_three in", values, "suggestionThree");
            return (Criteria) this;
        }

        public Criteria andSuggestionThreeNotIn(List<String> values) {
            addCriterion("suggestion_three not in", values, "suggestionThree");
            return (Criteria) this;
        }

        public Criteria andSuggestionThreeBetween(String value1, String value2) {
            addCriterion("suggestion_three between", value1, value2, "suggestionThree");
            return (Criteria) this;
        }

        public Criteria andSuggestionThreeNotBetween(String value1, String value2) {
            addCriterion("suggestion_three not between", value1, value2, "suggestionThree");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer_info
     *
     * @mbggenerated do_not_delete_during_merge Fri Jan 24 10:27:51 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}