package com.qtatelier.OASystem.basics.linkempdept.mapper;


import com.qtatelier.OASystem.basics.linkempdept.model.LinkEmpDept;

public interface LinkEmpDeptMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_emp_dept
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int deleteByPrimaryKey(String linkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_emp_dept
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int insert(LinkEmpDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_emp_dept
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int insertSelective(LinkEmpDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_emp_dept
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    LinkEmpDept selectByPrimaryKey(String linkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_emp_dept
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int updateByPrimaryKeySelective(LinkEmpDept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_emp_dept
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int updateByPrimaryKey(LinkEmpDept record);
}