package com.qtatelier.OASystem.basics.empinfo.mapper;


import com.qtatelier.OASystem.basics.empinfo.model.empInfo;

public interface empInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_info
     *
     * @mbggenerated Sun Jan 12 19:24:38 CST 2020
     */
    int deleteByPrimaryKey(String empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_info
     *
     * @mbggenerated Sun Jan 12 19:24:38 CST 2020
     */
    int insert(empInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_info
     *
     * @mbggenerated Sun Jan 12 19:24:38 CST 2020
     */
    int insertSelective(empInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_info
     *
     * @mbggenerated Sun Jan 12 19:24:38 CST 2020
     */
    empInfo selectByPrimaryKey(String empId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_info
     *
     * @mbggenerated Sun Jan 12 19:24:38 CST 2020
     */
    int updateByPrimaryKeySelective(empInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_info
     *
     * @mbggenerated Sun Jan 12 19:24:38 CST 2020
     */
    int updateByPrimaryKey(empInfo record);
}