package com.qtatelier.OASystem.basics.empinfo.mapper;


import com.qtatelier.OASystem.basics.empinfo.model.EmpInfo;

import java.util.List;

public interface EmpInfoMapper
{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey( String empId );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_info
     *
     * @mbg.generated
     */
    int insert( EmpInfo record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_info
     *
     * @mbg.generated
     */
    EmpInfo selectByPrimaryKey( String empId );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_info
     *
     * @mbg.generated
     */
    List<EmpInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table emp_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey( EmpInfo record );
}