package com.qtatelier.OASystem.basics.dutyinfo.mapper;


import com.qtatelier.OASystem.basics.dutyinfo.model.DutyInfo;
import com.qtatelier.OASystem.request.DutyReq;
import com.qtatelier.OASystem.response.DutyInfoRes;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface DutyInfoMapper
{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty_info
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey( String dutyId );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty_info
     *
     * @mbg.generated
     */
    int insert( DutyReq record );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty_info
     *
     * @mbg.generated
     */
    DutyInfo selectByPrimaryKey( String dutyId );

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty_info
     *
     * @mbg.generated
     */
    List<DutyInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table duty_info
     *
     * @mbg.generated
     */
    int updateByPrimaryKey( DutyInfo record );


    /**
     * @description 查出所有的部门职位
     * @return
     */
    List<DutyInfoRes> findAll();

}