package com.qtatelier.OASystem.basics.linkempuser.mapper;


import com.qtatelier.OASystem.basics.linkempuser.model.LinkEmpUser;

public interface LinkEmpUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_emp_user
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int deleteByPrimaryKey(String linkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_emp_user
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int insert(LinkEmpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_emp_user
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int insertSelective(LinkEmpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_emp_user
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    LinkEmpUser selectByPrimaryKey(String linkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_emp_user
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int updateByPrimaryKeySelective(LinkEmpUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_emp_user
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int updateByPrimaryKey(LinkEmpUser record);
}