package com.qtatelier.OASystem.basics.link_user_customer.mapper;

import com.qtatelier.OASystem.basics.link_user_customer.model.LinkUserCustomer;
import com.qtatelier.OASystem.basics.link_user_customer.model.LinkUserCustomerExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LinkUserCustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_user_customer
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int countByExample(LinkUserCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_user_customer
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int deleteByExample(LinkUserCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_user_customer
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int deleteByPrimaryKey(String linkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_user_customer
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int insert(LinkUserCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_user_customer
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int insertSelective(LinkUserCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_user_customer
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    List<LinkUserCustomer> selectByExample(LinkUserCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_user_customer
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    LinkUserCustomer selectByPrimaryKey(String linkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_user_customer
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") LinkUserCustomer record, @Param("example") LinkUserCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_user_customer
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int updateByExample(@Param("record") LinkUserCustomer record, @Param("example") LinkUserCustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_user_customer
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int updateByPrimaryKeySelective(LinkUserCustomer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table link_user_customer
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int updateByPrimaryKey(LinkUserCustomer record);
}