package com.qtatelier.OASystem.basics.userinfo.model;

import com.alibaba.fastjson.JSONObject;

import java.io.Serializable;

public class BlogUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.userName
     *
     * @mbg.generated
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.sign
     *
     * @mbg.generated
     */
    private String sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.location
     *
     * @mbg.generated
     */
    private String location;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.web_url
     *
     * @mbg.generated
     */
    private String webUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.callself
     *
     * @mbg.generated
     */
    private String callself;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.nick_name
     *
     * @mbg.generated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.image_name
     *
     * @mbg.generated
     */
    private String imageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.user_email
     *
     * @mbg.generated
     */
    private String userEmail;

    private String roleType;

    private String roleTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_user.token
     *
     * @mbg.generated
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table blog_user
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.user_id
     *
     * @return the value of blog_user.user_id
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.user_id
     *
     * @param userId the value for blog_user.user_id
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.userName
     *
     * @return the value of blog_user.userName
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.userName
     *
     * @param username the value for blog_user.userName
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.password
     *
     * @return the value of blog_user.password
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.password
     *
     * @param password the value for blog_user.password
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.sign
     *
     * @return the value of blog_user.sign
     * @mbg.generated
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.sign
     *
     * @param sign the value for blog_user.sign
     * @mbg.generated
     */
    public void setSign(String sign) {
        this.sign = sign == null ? null : sign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.location
     *
     * @return the value of blog_user.location
     * @mbg.generated
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.location
     *
     * @param location the value for blog_user.location
     * @mbg.generated
     */
    public void setLocation(String location) {
        this.location = location == null ? null : location.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.web_url
     *
     * @return the value of blog_user.web_url
     * @mbg.generated
     */
    public String getWebUrl() {
        return webUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.web_url
     *
     * @param webUrl the value for blog_user.web_url
     * @mbg.generated
     */
    public void setWebUrl(String webUrl) {
        this.webUrl = webUrl == null ? null : webUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.callself
     *
     * @return the value of blog_user.callself
     * @mbg.generated
     */
    public String getCallself() {
        return callself;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.callself
     *
     * @param callself the value for blog_user.callself
     * @mbg.generated
     */
    public void setCallself(String callself) {
        this.callself = callself == null ? null : callself.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.nick_name
     *
     * @return the value of blog_user.nick_name
     * @mbg.generated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.nick_name
     *
     * @param nickName the value for blog_user.nick_name
     * @mbg.generated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.image_name
     *
     * @return the value of blog_user.image_name
     * @mbg.generated
     */
    public String getImageName() {
        return imageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.image_name
     *
     * @param imageName the value for blog_user.image_name
     * @mbg.generated
     */
    public void setImageName(String imageName) {
        this.imageName = imageName == null ? null : imageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.user_email
     *
     * @return the value of blog_user.user_email
     * @mbg.generated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.user_email
     *
     * @param userEmail the value for blog_user.user_email
     * @mbg.generated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_user.token
     *
     * @return the value of blog_user.token
     * @mbg.generated
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_user.token
     *
     * @param token the value for blog_user.token
     * @mbg.generated
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }


    public String getRoleType() {
        return roleType;
    }

    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }

    public String getRoleTypeName() {
        return roleTypeName;
    }

    public void setRoleTypeName(String roleTypeName) {
        this.roleTypeName = roleTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_user
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        return JSONObject.toJSONString(this);
    }
}