package com.qtatelier.OASystem.basics.blogrole.model;

public class BlogRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_role.role_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_role.role_type_name
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    private String roleTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_role.role_type
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    private String roleType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_role.role_id
     *
     * @return the value of blog_role.role_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_role.role_id
     *
     * @param roleId the value for blog_role.role_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_role.role_type_name
     *
     * @return the value of blog_role.role_type_name
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public String getRoleTypeName() {
        return roleTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_role.role_type_name
     *
     * @param roleTypeName the value for blog_role.role_type_name
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public void setRoleTypeName(String roleTypeName) {
        this.roleTypeName = roleTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_role.role_type
     *
     * @return the value of blog_role.role_type
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public String getRoleType() {
        return roleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_role.role_type
     *
     * @param roleType the value for blog_role.role_type
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public void setRoleType(String roleType) {
        this.roleType = roleType;
    }
}