package com.qtatelier.OASystem.basics.customerinfo.mapper;

import com.qtatelier.OASystem.basics.customerinfo.model.CustomerInfo;
import com.qtatelier.OASystem.basics.customerinfo.model.CustomerInfoExample;
import com.qtatelier.OASystem.request.CustomerReq;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface CustomerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int countByExample(CustomerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int deleteByExample(CustomerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int deleteByPrimaryKey(String customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int insert(CustomerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int insertSelective(CustomerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    List<CustomerInfo> selectByExample(CustomerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    CustomerInfo selectByPrimaryKey(String customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int updateByExampleSelective(@Param("record") CustomerInfo record, @Param("example") CustomerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int updateByExample(@Param("record") CustomerInfo record, @Param("example") CustomerInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int updateByPrimaryKeySelective(CustomerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table customer_info
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    int updateByPrimaryKey(CustomerInfo record);



    List<CustomerInfo> selectByExampleInfo(CustomerReq customerReq);
}