package com.qtatelier.OASystem.basics.revisit_log.model;

public class RevisitLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revisit_log.revisit_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String revisitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revisit_log.revisit_log
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String revisitLog;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revisit_log.revisit_date
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String revisitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column revisit_log.revisit_tel
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    private String revisitTel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revisit_log.revisit_id
     *
     * @return the value of revisit_log.revisit_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getRevisitId() {
        return revisitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revisit_log.revisit_id
     *
     * @param revisitId the value for revisit_log.revisit_id
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setRevisitId(String revisitId) {
        this.revisitId = revisitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revisit_log.revisit_log
     *
     * @return the value of revisit_log.revisit_log
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getRevisitLog() {
        return revisitLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revisit_log.revisit_log
     *
     * @param revisitLog the value for revisit_log.revisit_log
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setRevisitLog(String revisitLog) {
        this.revisitLog = revisitLog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revisit_log.revisit_date
     *
     * @return the value of revisit_log.revisit_date
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getRevisitDate() {
        return revisitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revisit_log.revisit_date
     *
     * @param revisitDate the value for revisit_log.revisit_date
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setRevisitDate(String revisitDate) {
        this.revisitDate = revisitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column revisit_log.revisit_tel
     *
     * @return the value of revisit_log.revisit_tel
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public String getRevisitTel() {
        return revisitTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column revisit_log.revisit_tel
     *
     * @param revisitTel the value for revisit_log.revisit_tel
     *
     * @mbggenerated Fri Jan 24 10:27:51 CST 2020
     */
    public void setRevisitTel(String revisitTel) {
        this.revisitTel = revisitTel;
    }
}