package com.qtatelier.OASystem.basics.deptinfo.model;

public class DeptInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_info.dept_id
     *
     * @mbggenerated Sun Jan 12 20:39:50 CST 2020
     */
    private String deptId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_info.dept_no
     *
     * @mbggenerated Sun Jan 12 20:39:50 CST 2020
     */
    private String deptNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_info.dept_name
     *
     * @mbggenerated Sun Jan 12 20:39:50 CST 2020
     */
    private String deptName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_info.dept_desc
     *
     * @mbggenerated Sun Jan 12 20:39:50 CST 2020
     */
    private String deptDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dept_info.dept_order
     *
     * @mbggenerated Sun Jan 12 20:39:50 CST 2020
     */
    private String deptOrder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_info.dept_id
     *
     * @return the value of dept_info.dept_id
     *
     * @mbggenerated Sun Jan 12 20:39:50 CST 2020
     */
    public String getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_info.dept_id
     *
     * @param deptId the value for dept_info.dept_id
     *
     * @mbggenerated Sun Jan 12 20:39:50 CST 2020
     */
    public void setDeptId(String deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_info.dept_no
     *
     * @return the value of dept_info.dept_no
     *
     * @mbggenerated Sun Jan 12 20:39:50 CST 2020
     */
    public String getDeptNo() {
        return deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_info.dept_no
     *
     * @param deptNo the value for dept_info.dept_no
     *
     * @mbggenerated Sun Jan 12 20:39:50 CST 2020
     */
    public void setDeptNo(String deptNo) {
        this.deptNo = deptNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_info.dept_name
     *
     * @return the value of dept_info.dept_name
     *
     * @mbggenerated Sun Jan 12 20:39:50 CST 2020
     */
    public String getDeptName() {
        return deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_info.dept_name
     *
     * @param deptName the value for dept_info.dept_name
     *
     * @mbggenerated Sun Jan 12 20:39:50 CST 2020
     */
    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_info.dept_desc
     *
     * @return the value of dept_info.dept_desc
     *
     * @mbggenerated Sun Jan 12 20:39:50 CST 2020
     */
    public String getDeptDesc() {
        return deptDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_info.dept_desc
     *
     * @param deptDesc the value for dept_info.dept_desc
     *
     * @mbggenerated Sun Jan 12 20:39:50 CST 2020
     */
    public void setDeptDesc(String deptDesc) {
        this.deptDesc = deptDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dept_info.dept_order
     *
     * @return the value of dept_info.dept_order
     *
     * @mbggenerated Sun Jan 12 20:39:50 CST 2020
     */
    public String getDeptOrder() {
        return deptOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dept_info.dept_order
     *
     * @param deptOrder the value for dept_info.dept_order
     *
     * @mbggenerated Sun Jan 12 20:39:50 CST 2020
     */
    public void setDeptOrder(String deptOrder) {
        this.deptOrder = deptOrder;
    }
}