package com.qtatelier.OASystem.basics.linkempuser.model;

public class LinkEmpUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_emp_user.link_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    private String linkId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_emp_user.emp_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    private String empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column link_emp_user.user_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    private String userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_emp_user.link_id
     *
     * @return the value of link_emp_user.link_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public String getLinkId() {
        return linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_emp_user.link_id
     *
     * @param linkId the value for link_emp_user.link_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public void setLinkId(String linkId) {
        this.linkId = linkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_emp_user.emp_id
     *
     * @return the value of link_emp_user.emp_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public String getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_emp_user.emp_id
     *
     * @param empId the value for link_emp_user.emp_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public void setEmpId(String empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column link_emp_user.user_id
     *
     * @return the value of link_emp_user.user_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column link_emp_user.user_id
     *
     * @param userId the value for link_emp_user.user_id
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }
}