package com.qtatelier.OASystem.basics.blogrole.mapper;


import com.qtatelier.OASystem.basics.blogrole.model.BlogRole;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface BlogRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_role
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int deleteByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_role
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int insert(BlogRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_role
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int insertSelective(BlogRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_role
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    BlogRole selectByPrimaryKey(String roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_role
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int updateByPrimaryKeySelective(BlogRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_role
     *
     * @mbggenerated Sun Jan 12 19:30:26 CST 2020
     */
    int updateByPrimaryKey(BlogRole record);
}